apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-red-deployment
spec:
  replicas: 1
  type: LoadBalancer
  template:
    metadata:
      labels:
        app: node-red
    spec:
      containers:
        - name: node-red
          image: nodered/node-red:latest
          ports:
            - containerPort: 1880
              protocol: TCP
          volumeMounts: 
            - name: node-red-directory
              mountPath: /data
      volumes:
        - name: node-red-directory
          persistentVolumeClaim:
            claimName: node-red-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: node-red-service
  labels:
    app: node-red-service
    kubernetes.io/name: "node-red-service"
spec:
  selector:
    app: node-red-service
  ports:
    - protocol: TCP
      port: 1880
      targetPort: 1880
      name: node-red
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: node-red 
spec:
  host: nodered.student297.rahtiapp.fi
  to: 
    kind: Service
    name: node-red-service
  port:
    targetPort: 1880