apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    allow_anonymous true
    listener 1883
    listener 8883
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mosquito-deployment
spec:
  replicas: 1
  type: ClusterIP
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:latest
          ports:
            - containerPort: 1883
              protocol: TCP
            - containerPort: 8883
              protocol: TCP
          volumeMounts: 
            - name: mosquitto-conf
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf 
            - name: mosquitto-secret
              mountPath: /mosquitto/secret
              readOnly: true
      volumes:
        - name: mosquitto-conf
          configMap:
            name: mosquitto-config
        - name: mosquitto-secret
          secret :
            secretName: mosquitto-secret-file
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  labels:
    app: mosquitto-service
    kubernetes.io/name: "mosquitto-service"
spec:
  selector:
    app: mosquitto-service
  ports:
    - protocol: TCP
      port: 8883
      targetPort: 8883
      name: mosquitto-tls
    - protocol: TCP
      port: 1883
      targetPort: 1883
      name: mosquitto
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mosquitto 
spec:
  host: mqtt.student297.rahtiapp.fi
  to: 
    kind: Service
    name: mosquitto-service
  port:
    targetPort: 8883
  tls:
    termination: passthrough